# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import notification_pb2 as proto_dot_notification__pb2


class NotificationControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotification = channel.unary_unary(
                '/account.NotificationController/CreateNotification',
                request_serializer=proto_dot_notification__pb2.NotificationRequest.SerializeToString,
                response_deserializer=proto_dot_notification__pb2.Notification.FromString,
                )
        self.CreateNotificationType = channel.unary_unary(
                '/account.NotificationController/CreateNotificationType',
                request_serializer=proto_dot_notification__pb2.NotificationTypeRequest.SerializeToString,
                response_deserializer=proto_dot_notification__pb2.NotificationType.FromString,
                )
        self.UpdateNotification = channel.unary_unary(
                '/account.NotificationController/UpdateNotification',
                request_serializer=proto_dot_notification__pb2.NotificationRequest.SerializeToString,
                response_deserializer=proto_dot_notification__pb2.Notification.FromString,
                )
        self.DestroyNotification = channel.unary_unary(
                '/account.NotificationController/DestroyNotification',
                request_serializer=proto_dot_notification__pb2.NotificationRetrieveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class NotificationControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNotificationType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=proto_dot_notification__pb2.NotificationRequest.FromString,
                    response_serializer=proto_dot_notification__pb2.Notification.SerializeToString,
            ),
            'CreateNotificationType': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotificationType,
                    request_deserializer=proto_dot_notification__pb2.NotificationTypeRequest.FromString,
                    response_serializer=proto_dot_notification__pb2.NotificationType.SerializeToString,
            ),
            'UpdateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotification,
                    request_deserializer=proto_dot_notification__pb2.NotificationRequest.FromString,
                    response_serializer=proto_dot_notification__pb2.Notification.SerializeToString,
            ),
            'DestroyNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyNotification,
                    request_deserializer=proto_dot_notification__pb2.NotificationRetrieveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account.NotificationController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account.NotificationController/CreateNotification',
            proto_dot_notification__pb2.NotificationRequest.SerializeToString,
            proto_dot_notification__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNotificationType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account.NotificationController/CreateNotificationType',
            proto_dot_notification__pb2.NotificationTypeRequest.SerializeToString,
            proto_dot_notification__pb2.NotificationType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account.NotificationController/UpdateNotification',
            proto_dot_notification__pb2.NotificationRequest.SerializeToString,
            proto_dot_notification__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account.NotificationController/DestroyNotification',
            proto_dot_notification__pb2.NotificationRetrieveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
