# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proto.account_pb2 as account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification.proto',
  package='account',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12notification.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\x1a\raccount.proto\"_\n\x10NotificationType\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04icon\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x11\n\twebserver\x18\x05 \x01(\x05\"\x92\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x14\n\x0c\x63reated_date\x18\x03 \x01(\t\x12\x13\n\x0bsender_name\x18\x04 \x01(\t\x12\x10\n\x08icon_URL\x18\x05 \x01(\t\x12\x10\n\x08receiver\x18\x06 \x01(\x05\x12\x19\n\x11notification_type\x18\x07 \x01(\x05\"\x1c\n\x0eNotificationId\x12\n\n\x02id\x18\x01 \x01(\x05\"a\n\x13NotificationRequest\x12\x1d\n\x05login\x18\x01 \x01(\x0b\x32\x0e.account.Login\x12+\n\x0cnotification\x18\x02 \x01(\x0b\x32\x15.account.Notification\"n\n\x17NotificationTypeRequest\x12\x1d\n\x05login\x18\x01 \x01(\x0b\x32\x0e.account.Login\x12\x34\n\x11notification_type\x18\x02 \x01(\x0b\x32\x19.account.NotificationType\"k\n\x1bNotificationRetrieveRequest\x12\x1d\n\x05login\x18\x01 \x01(\x0b\x32\x0e.account.Login\x12-\n\x0cnotification\x18\x02 \x01(\x0b\x32\x17.account.NotificationId2\x95\x02\n\x16NotificationController\x12K\n\x12\x43reateNotification\x12\x1c.account.NotificationRequest\x1a\x15.account.Notification\"\x00\x12W\n\x16\x43reateNotificationType\x12 .account.NotificationTypeRequest\x1a\x19.account.NotificationType\"\x00\x12U\n\x13\x44\x65stroyNotification\x12$.account.NotificationRetrieveRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,])




_NOTIFICATIONTYPE = _descriptor.Descriptor(
  name='NotificationType',
  full_name='account.NotificationType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='account.NotificationType.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='account.NotificationType.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='account.NotificationType.icon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='account.NotificationType.priority', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='webserver', full_name='account.NotificationType.webserver', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=170,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='account.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='account.Notification.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='account.Notification.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_date', full_name='account.Notification.created_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_name', full_name='account.Notification.sender_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_URL', full_name='account.Notification.icon_URL', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='account.Notification.receiver', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification_type', full_name='account.Notification.notification_type', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=319,
)


_NOTIFICATIONID = _descriptor.Descriptor(
  name='NotificationId',
  full_name='account.NotificationId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='account.NotificationId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=349,
)


_NOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='NotificationRequest',
  full_name='account.NotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='account.NotificationRequest.login', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification', full_name='account.NotificationRequest.notification', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=448,
)


_NOTIFICATIONTYPEREQUEST = _descriptor.Descriptor(
  name='NotificationTypeRequest',
  full_name='account.NotificationTypeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='account.NotificationTypeRequest.login', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification_type', full_name='account.NotificationTypeRequest.notification_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=560,
)


_NOTIFICATIONRETRIEVEREQUEST = _descriptor.Descriptor(
  name='NotificationRetrieveRequest',
  full_name='account.NotificationRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='account.NotificationRetrieveRequest.login', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification', full_name='account.NotificationRetrieveRequest.notification', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=669,
)

_NOTIFICATIONREQUEST.fields_by_name['login'].message_type = account__pb2._LOGIN
_NOTIFICATIONREQUEST.fields_by_name['notification'].message_type = _NOTIFICATION
_NOTIFICATIONTYPEREQUEST.fields_by_name['login'].message_type = account__pb2._LOGIN
_NOTIFICATIONTYPEREQUEST.fields_by_name['notification_type'].message_type = _NOTIFICATIONTYPE
_NOTIFICATIONRETRIEVEREQUEST.fields_by_name['login'].message_type = account__pb2._LOGIN
_NOTIFICATIONRETRIEVEREQUEST.fields_by_name['notification'].message_type = _NOTIFICATIONID
DESCRIPTOR.message_types_by_name['NotificationType'] = _NOTIFICATIONTYPE
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['NotificationId'] = _NOTIFICATIONID
DESCRIPTOR.message_types_by_name['NotificationRequest'] = _NOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['NotificationTypeRequest'] = _NOTIFICATIONTYPEREQUEST
DESCRIPTOR.message_types_by_name['NotificationRetrieveRequest'] = _NOTIFICATIONRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationType = _reflection.GeneratedProtocolMessageType('NotificationType', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONTYPE,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.NotificationType)
  })
_sym_db.RegisterMessage(NotificationType)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.Notification)
  })
_sym_db.RegisterMessage(Notification)

NotificationId = _reflection.GeneratedProtocolMessageType('NotificationId', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONID,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.NotificationId)
  })
_sym_db.RegisterMessage(NotificationId)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

NotificationTypeRequest = _reflection.GeneratedProtocolMessageType('NotificationTypeRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONTYPEREQUEST,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.NotificationTypeRequest)
  })
_sym_db.RegisterMessage(NotificationTypeRequest)

NotificationRetrieveRequest = _reflection.GeneratedProtocolMessageType('NotificationRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONRETRIEVEREQUEST,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:account.NotificationRetrieveRequest)
  })
_sym_db.RegisterMessage(NotificationRetrieveRequest)



_NOTIFICATIONCONTROLLER = _descriptor.ServiceDescriptor(
  name='NotificationController',
  full_name='account.NotificationController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=672,
  serialized_end=949,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateNotification',
    full_name='account.NotificationController.CreateNotification',
    index=0,
    containing_service=None,
    input_type=_NOTIFICATIONREQUEST,
    output_type=_NOTIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateNotificationType',
    full_name='account.NotificationController.CreateNotificationType',
    index=1,
    containing_service=None,
    input_type=_NOTIFICATIONTYPEREQUEST,
    output_type=_NOTIFICATIONTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DestroyNotification',
    full_name='account.NotificationController.DestroyNotification',
    index=2,
    containing_service=None,
    input_type=_NOTIFICATIONRETRIEVEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTIFICATIONCONTROLLER)

DESCRIPTOR.services_by_name['NotificationController'] = _NOTIFICATIONCONTROLLER

# @@protoc_insertion_point(module_scope)
